require("config.keymaps")
require("config.options")

require("plugins.tmux")
require("plugins.oil")
require("plugins.oil-git-status")
require("plugins.smear-cursor")
require("plugins.theme")
require("plugins.bufferline")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.metals")
require("plugins.lualine")
require("plugins.mini")
require("plugins.notice")
require("plugins.todo-comments")
